import React from 'react';
import jsPDF from 'jspdf';
import { EvaluationResult } from '../types';

const SECTION_LABELS: Record<string, string> = {
  open_source:      'Open Source',
  self_projects:    'Self Projects',
  production:       'Production Experience',
  technical_skills: 'Technical Skills',
};

interface Props {
  result: EvaluationResult;
}

export default function ReportDownload({ result }: Props) {
  const generate = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    const line = (text: string, size = 11, bold = false) => {
      doc.setFontSize(size);
      doc.setFont('helvetica', bold ? 'bold' : 'normal');
      const lines = doc.splitTextToSize(text, 170);
      lines.forEach((l: string) => {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.text(l, margin, y);
        y += size * 0.5 + 2;
      });
    };

    const spacer = (n = 6) => { y += n; };

    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('ResuEdge — Resume Evaluation Report', margin, 20);
    doc.setTextColor(0, 0, 0);
    y = 42;

    // Candidate + overall score
    line(`Candidate: ${result.candidate_name}`, 13, true);
    line(`Overall Score: ${result.total_score} / ${result.max_score}`, 13, true);
    if (result.bonus_points.total > 0)
      line(`Bonus Points: +${result.bonus_points.total} — ${result.bonus_points.breakdown}`, 10);
    if (result.deductions.total > 0)
      line(`Deductions: -${result.deductions.total} — ${result.deductions.reasons}`, 10);
    spacer();

    // Section scores
    line('Section Scores', 13, true);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, 190, y); y += 4;
    Object.entries(result.scores).forEach(([key, cat]) => {
      line(`${SECTION_LABELS[key] || key}: ${cat.score} / ${cat.max}`, 11, true);
      line(cat.evidence, 10);
      spacer(3);
    });
    spacer();

    // Suggestions
    if (Object.keys(result.suggestions).length > 0) {
      line('Improvement Suggestions', 13, true);
      doc.line(margin, y, 190, y); y += 4;
      Object.entries(result.suggestions).forEach(([key, sec]) => {
        line(`${SECTION_LABELS[key] || key} — ${sec.priority} Priority`, 12, true);
        line(sec.reason, 10);
        spacer(2);
        sec.suggestions.forEach((s, i) => {
          line(`${i + 1}. ${s.title}`, 11, true);
          line(`Action: ${s.action}`, 10);
          line(`Why it helps: ${s.why}`, 10);
          spacer(3);
        });
        spacer(2);
      });
    }

    // Key strengths
    if (result.key_strengths.length > 0) {
      line('Key Strengths', 13, true);
      doc.line(margin, y, 190, y); y += 4;
      result.key_strengths.forEach(s => line(`• ${s}`, 10));
      spacer();
    }

    // Footer
    if (y > 265) { doc.addPage(); y = 20; }
    y = 285;
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by ResuEdge — resumeedge.app', margin, y);

    doc.save(`ResuEdge_${result.candidate_name.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <button className="btn-download" onClick={generate}>
      ⬇️ Download PDF Report
    </button>
  );
}
